<?php

/**
 * @file
 * Hook implementations for elasticsearch_helper_aws.
 */

use Elasticsearch\ClientBuilder;
use Aws\Credentials\CredentialProvider;
use Aws\Credentials\Credentials;
use Aws\ElasticsearchService\ElasticsearchPhpHandler;

/**
 * Implements hook_elasticsearch_helper_client_builder_alter().
 */
function elasticsearch_helper_aws_elasticsearch_helper_client_builder_alter(ClientBuilder $clientBuilder) {
  $config = \Drupal::config('elasticsearch_helper_aws.settings');
  $access_key_id = $config->get('access_key_id');
  $secret_access_key = $config->get('secret_access_key');
  $region = $config->get('region');

  if ($access_key_id && $secret_access_key && $region) {
    $provider = CredentialProvider::fromCredentials(
      new Credentials($access_key_id, $secret_access_key)
    );

    $handler = new ElasticsearchPhpHandler($region, $provider);

    $clientBuilder->setHandler($handler);
  }
}
